### ISSUE TITLE
[Feature-Request] Close file preview with ESC-Key

### ISSUE THREAD

**Issue by revlov** [SeeSharpSoft/intellij-file-preview#11]
As a user I want to be able to close the **file preview tab** by hitting the `ESC-Key`, so in case I accidentally clicked a file for preview, I immediately can close the spawned tab.

**Comment by SeeSharpSoft** [comment]
[Quick navigation key bindings](https://github.com/SeeSharpSoft/intellij-file-preview#enable-quick-navigation-key-events-activated) added in Release 1.3.0
