### ISSUE TITLE
Enabling in PHPStorm?

### ISSUE THREAD

**Issue by nrutman** [SeeSharpSoft/intellij-file-preview#15]
Hello. I'm trying to use this plugin in PHPStorm 2019.2. I've installed it from the marketplace and restarted the IDE several times, but when I click on a file in the project view it opens as a normal tab.

Do I need to do something within the editor to enable the preview?

**Comment by SeeSharpSoft** [comment]
This is most likely related to issue #3 - Release 1.2.1 is still pending Jetbrains approval. Still you can give it a try by [downloading](https://github.com/SeeSharpSoft/intellij-file-preview/releases/download/1.2.1/file-preview-1.2.1.jar) and [installing](https://github.com/SeeSharpSoft/intellij-file-preview#installation) the [release](https://github.com/SeeSharpSoft/intellij-file-preview/releases/tag/1.2.1) from disc.
