### ISSUE TITLE
UX: ESC keyboard shortcut should only ever close Preview windows, not other tabs with files "really opened," and definitely not Pinned tabs.

### ISSUE THREAD

**Issue by bronius** [SeeSharpSoft/intellij-file-preview#19]
I love that ESC can close a Preview window and that hitting TAB gets you into the Preview so that ESC _would not_ close the tab. However, hitting ESC _should not_ close non-Preview-opened tabs ever.

## Steps to Reproduce
1. With the plugin enabled and working
1. With some file(s) opened
1. With some file(s) pinned
1. Click in Projects pane to open a Quick File Preview tab
1. Hit ESC and watch with joy as the Preview tab closes
1. But hit ESC again ..  and watch with dismay as another non-preview tab closes
1. Continued hitting ESC again, and watch in shock and horror as remaining tabs, even pinned ones, close one-by-one.. 😢 

(This really is a great plugin - Please see through my jovial silliness to the point of my request here and do not take it as any disrespect to you or your fantastic feature-add to PHP Storm! I'm so grateful for this feature!)

**Comment by SeeSharpSoft** [comment]
@bronius Interesting - I am using the plugin myself and found it very convenient to be able to close all tabs by pressing ESC.

However, I see how this might influences the well known UX of the IDE. Therefore, I will change the default behavior, so the general additional [Quick Navigation Key Events option](https://github.com/SeeSharpSoft/intellij-file-preview#enable-quick-navigation-key-events-activated) is not enabled but ESC still closes the preview.

**Comment by bronius** [comment]
Confirmed in latest release :D It's working great -- thank you!!
