### ISSUE TITLE
UX: Always cycle out the single, open Preview tab so that only one Preview is ever open at a time

### ISSUE THREAD

**Issue by bronius** [SeeSharpSoft/intellij-file-preview#20]
Since this PHP Storm Quick File Preview plugin is modeled after the observed and beloved behavior of editors like Sublime, one little thing that sets it apart is that Preview windows stack instead of auto-closing and re-opening with each fresh new Preview.

## Steps to Reproduce
1. With the plugin active and working
1. Click a file in the Projects pane to open a Quick File Preview preview
1. Click another file
**Expected behavior:**
The new file will replace the existing file preview tab.
**Instead:**
Each new file clicked opens an additional Preview tab.

(This may be what the existing 2nd option in plugin settings is about, but due to #18 I can't confirm, so I'll just file away my thoughts here in the meantime. Maybe it's related to some other "conflicting" IDE native preference I set long ago in want of this plugin..)

**Comment by SeeSharpSoft** [comment]
@bronius Thanks for reporting - but when I understand it right then the described behavior would negate the whole purpose of the plugin (which would be really bad!). However, I can't reproduce this behavior.

**a)** Can you please check whether this might be cause of "Autoscroll to Source" option as described in #17
**b)** If not a), can you please add a the IDE version and a screenshot of those multiple preview tabs.

Thanks!

**Comment by bronius** [comment]
Quite so! #17 Indeed I have (had) Autoscroll to Source enabled:
![autoscroll to source option](https://user-images.githubusercontent.com/2348390/62727968-43a1c980-b9e0-11e9-9e62-c29f20fd2c7b.jpg)

I'll keep my Autoscroll to source disabled for a bit and see how it feels with this great preview working as it was intended 😄 Thanks for checking it out and pointing me in the right direction!
