### ISSUE TITLE
It is not opening a directory in one click

### ISSUE THREAD

**Issue by Mykola-Veriga** [SeeSharpSoft/intellij-file-preview#24]
It is not opening a directory in one click

**Comment by Mykola-Veriga** [comment]
Sorry, it is just useless plugin. It doesn't have sublime features

**Comment by SeeSharpSoft** [comment]
@Mykola-Veriga I never used sublime, I do not know the features of sublime, I do not aim to clone sublime nor having the exact same features if not required. The goal is to have a useful and better navigation that fits the IntelliJ IDE.

What kind of other features do you miss?

**Comment by Mykola-Veriga** [comment]
one thing I like about using a sublime is that I can click once on the left directory and the directory I choose shows up. 
With PhpStorm, I have to double click, which makes for lots of double clicking ...
