### ISSUE TITLE
[Feature-Request] Show file/class Structure details while in preview

### ISSUE THREAD

**Issue by bronius** [SeeSharpSoft/intellij-file-preview#25]
While clicking around files, it would be nice to see the Structure pane (if it is open) to be populated with the currently active files in Preview. Of course, as the Preview is closed, the Structure pane would go blank again.

## Use cases:
This is useful when thumbing through files in a non-committal way (the point of Quick File Preview) and seeing at a glance what methods and properties are provided by each file in Preview.

**Comment by SeeSharpSoft** [comment]
@bronius I do not understand the request, this is default IntelliJ IDE behavior and already working out of the box:
![image](https://user-images.githubusercontent.com/3205800/62891084-1c7f2b00-bd45-11e9-85a6-07005da27255.png)
(switching files will also update the structure view)

What am I missing?

**Comment by bronius** [comment]
Thanks for taking the time to take in my request and validate (or invalidate!) it. I just checked on my end again to see if I was just crazy: It turns out that _sometimes_ they should and other times they do not! I haven't found a pattern yet because it's not always the same files that open or don't open:

After reading your response, I headed back to PhpStorm and cursored up and down the Projects pane: All yml files Previewed and opened Structure just fine. Not all .php Class files did, but some did. I _feel_ that the ones that did were consistently the ones that did show something in Structure. I double-clicked and opened a lot of them, and by cusoring up and down with the keyboard arrow keys again, I confirmed they all showed in Structure. I closed all the edit tabs and cursored up and down in Projects again: This time _no_ .php files previewed, but all .ymls did still.

Once for good measure, hoping this would reset the behavior, I closed PhpStorm and launched again: Same behavior: No .php file Previews would also show in Structure, but all .yml Previews do.

**Comment by SeeSharpSoft** [comment]
@bronius Thanks for the investigation - I could reproduce the described behavior with PHP files. I have to investigate further to narrow down what causes this behavior.

**Comment by bronius** [comment]
Interesting. Thank you for your interest and taking the time to check it out. If I figure out any other details I'll be sure to share as well. Maybe something with indexing caching, internal to PhpStorm.

**Comment by bronius** [comment]
I'm sure this is not a huge thing, but please be aware that something is still funny on my end with regard to Preview and seeing Structure, even after the update.

Thanks for the update! .. . but I still don't see 100% PHP files previewing:
https://hostfast.onlineconverter.com/file/1203a48f33897a9bac915112f236f0793a/download
(I don't know how long this 3MB screencast mp4 will remain available online.. says 24hrs)

**Comment by SeeSharpSoft** [comment]
It comes with [release 1.4.1](https://github.com/SeeSharpSoft/intellij-file-preview/releases/tag/1.4.1) - approval still pending to be available in Jetbrains plugin repository.

**Comment by bronius** [comment]
I'm sorry I missed this until now-- came here to confirm it working as expected! Thank you 😁💯
