### ISSUE TITLE
Unreliable PreviewStartupActivity#register

### ISSUE THREAD

**Issue by krasa** [SeeSharpSoft/intellij-file-preview#3]
You need to do it on EDT, otherwise ProjectViewPane can be null and it will never be registered for a project, if you look into `com.intellij.ide.projectView.impl.ProjectViewImpl#getProjectViewPaneById`...
```
    if (!ApplicationManager.getApplication().isUnitTestMode() && ApplicationManager.getApplication().isDispatchThread()) {
      // most tests don't need all panes to be loaded, but also we should not initialize panes on background threads
      ensurePanesLoaded();
    }
```

**Comment by SeeSharpSoft** [comment]
Fixed in Release [1.2.1](https://github.com/SeeSharpSoft/intellij-file-preview/releases/tag/1.2.1)
