### ISSUE TITLE
Plugin is broken in last version

### ISSUE THREAD

**Issue by mallowigi** [SeeSharpSoft/intellij-file-preview#30]
I just updated this plugin and the preview functionality no longer works, e.g. I can't make the previewed tab appear.

I have rollbacked to 1.3.1 in the meantime

**Comment by SeeSharpSoft** [comment]
@mallowigi Thanks for reporting! Can you please provide any additional information, e.g. IDE type/version, editor related settings (like [Scroll to/from Source](https://www.jetbrains.com/help/idea/navigating-through-the-source-code.html#scroll_to_from_source)) or other settings as used in #29. I currently can not reproduce the issue.

**Comment by SeeSharpSoft** [comment]
[Release 1.4.1](https://github.com/SeeSharpSoft/intellij-file-preview/releases/tag/1.4.1) available - also soon in JetBrains plugin repository...
