### ISSUE TITLE
[BUG] Previous file previews should not show up in "recent files"-view/panel (CTRL+E)

### ISSUE THREAD

**Issue by revlov** [SeeSharpSoft/intellij-file-preview#4]
Previewed files should not show up in "recent files"-view/panel. This panel gets full pretty
fast when navigating through the project.

There might be a use case while you are debugging. (fx. Breakpoint stops) But that should be optional imo.

---

![recent files](https://user-images.githubusercontent.com/53493119/62161102-b8f10880-b315-11e9-81e2-e31bcdbbf65e.png)

The "recent files"-view/panel should not contain previewed files.  
However, if others might benefit from having them in the "recent files"-view/panel, a setting should be made available to choose the behavior.

**Comment by SeeSharpSoft** [comment]
Fixed in [Release 1.2.1](https://github.com/SeeSharpSoft/intellij-file-preview/releases/tag/1.2.1)
