### ISSUE TITLE
When using navigate ctrl-F12 or F12 it will leaves the explorer focused

### ISSUE THREAD

**Issue by rluiten** [SeeSharpSoft/intellij-file-preview#43]
It will not always leave the Explorer focused, but its pretty common.

I am on Windows 10.
I am running JetBrains Rider 20019.2 Build #RD-192.6584.65, built on August 29, 2019.
It seems to only happen with Quick File Preview enabled I am running v1.4.6.

I like the preview, but the focus change from editor to explorer is driving me a little crazy :).

A sure fire for me to see it happen is to close Rider, reload it with my project pick an identifier and navigate to declaration or usages using F12. Hmm seems my sure fire isn't, it will not focus the explorer some times.

**Comment by SeeSharpSoft** [comment]
Thanks for reporting! Can you please help me understand the issue better:

- What is F12 or Ctrl+F12 supposed to do in Rider (I never used Rider)?
- What is respectively the expected/default behavior, and what is the unwanted behavior with Quick File Preview? (I didn't get whether the project view is expected to get or keep the focus, or the opposite)

When you switch off the "Focus Project View after opening/closing file editor" setting, does this behavior still remain?
![image](https://user-images.githubusercontent.com/3205800/65624088-6eb09e80-dfc9-11e9-9e6a-e7516606b781.png)

**Comment by rluiten** [comment]
F12 is "Navigate to Declaration or Usages".
ctl-F12 is "Navigate to Implementation(s)"

The behavior I expect is that navigate to another source file will focus the tab the target source file is 
in or load it and focus it if its not an existing tab.

Having focus moved to explorer view means that for example hitting ctrl-minus to go back to the source location from where "navigate to implementation" moved  me collapses the the explorer content. or pressing cursor up if the explorer pane is focused selects the file above the one I have been navigated to for display.

It appear disabling "Focus Project Vie after opening/closing file editor" stops the behavior I am seeing. Yay!.... :)

**Comment by SeeSharpSoft** [comment]
Should be generally resolved by now.
