### ISSUE TITLE
Switching tab with hotkey leaves focus on explorer with Autoscroll from Source

### ISSUE THREAD

**Issue by davidtoulmin** [SeeSharpSoft/intellij-file-preview#44]
I'm using PyCharm (2019.2.3 Community Edition) on Ubuntu (18.04.3), and switching tabs ('Select Next Tab' and 'Select Previous Tab') with original hotkey ('Alt+Right' and 'Alt+Left') or personal keymap ('Ctrl+Tab' and 'Ctrl+Shift+Tab') with 'Autoscroll from Source' turned on will switch tab correctly, but will also switch focus to the explorer, so any further tab shifts just change the explorer's scope instead.

**Comment by SeeSharpSoft** [comment]
You can switch off the "Focus Project View after opening/closing file editor" setting:
![image](https://user-images.githubusercontent.com/3205800/65666997-1d42f680-e03f-11e9-823b-720bad115111.png)

Additionally I will check whether I can improve the focusing behavior.

**Comment by davidtoulmin** [comment]
I already have "Focus Project View after opening/closing file editor" turned on. Given that; let me clarify:
Expected behaviour with 'Autoscroll from Source' enabled, and "Quick File Preview" enabled; Alt+Right moves to tab one right of current tab, and leaves focus on that tab.
Actual behaviour with 'Autoscroll from Source' enabled, and "Quick File Preview" disabled; Alt+Right moves to tab one right of current tab, and leaves focus on that tab.
Actual behaviour with 'Autoscroll from Source' enabled, and "Quick File Preview" enabled; Alt+Right moves to tab one right of current tab, and moves focus to explorer.

Interestingly: Actual behaviour with 'Autoscroll from Source' disabled, and "Quick File Preview" enabled; Alt+Right moves to tab one right of current tab, and leaves focus on that tab.
But I want 'Autoscroll from Source' enabled.

TDLR:
Expected behaviour with 'Autoscroll from Source' enabled, and "Quick File Preview" enabled; Alt+Right moves to tab one right of current tab, and leaves focus on that tab.
Actual behaviour with 'Autoscroll from Source' enabled, and "Quick File Preview" enabled; Alt+Right moves to tab one right of current tab, and moves focus to explorer.

**Comment by SeeSharpSoft** [comment]
As I wrote, please switch **OFF** the "Focus Project View after opening/closing file editor" setting - it is ON by default

**Comment by davidtoulmin** [comment]
I tried that, it didn't have any effect, it's still acting the same.

**Comment by SeeSharpSoft** [comment]
Then I can not reproduce this behavior, as locally it behaves like this: With the setting turned ON, it was exactly as you described, and by switching it OFF the behavior was as you described to be expected.

Can you provide any additional information (any other settings that might impact the editor behavior)?

> I'm not sure why this would have an effect, as I'm not opening or closing files, but switching between already open files.

Another file is selected in the project view, which triggers internally a call to open a file. In case it is already open, it is focused automatically. This is default IntelliJ behavior.

**Comment by davidtoulmin** [comment]
> With the setting turned ON,

> and by switching it OFF

With what setting on or off? And you have "Autoscroll from Source" switched on? Does switching Autoscroll from Source on/off change the behaviour?

**Comment by SeeSharpSoft** [comment]
I am talking about "Focus Project View after opening/closing file editor" setting - I do understand that you want to use "Autoscroll from Source"

**Comment by davidtoulmin** [comment]
So turning on/off "Autoscroll from Source" doesn't change anything for you?

**Comment by SeeSharpSoft** [comment]
> So turning on/off "Autoscroll from Source" doesn't change anything for you?

When "Autoscroll from Source" is **enabled**:

> With the setting **"Focus Project View after opening/closing file editor"** turned ON, it was exactly as you described, and by switching it (the setting **"Focus Project View after opening/closing file editor"**) OFF the behavior was as you described to be expected.

**Comment by davidtoulmin** [comment]
Huh, weird, I wonder what's different between our set-ups, because for me, turning off "Focus Project View after opening/closing file editor" didn't change anything. Oh well, I guess I can't use the preview plugin. Thanks for your help anyway.

**Comment by SeeSharpSoft** [comment]
I'll keep the issue open for now and investigate further.

**Comment by SeeSharpSoft** [comment]
I figured out the difference in our setups: When switching the Project View to "Open Files" (which also happens via ALT+Left/Right and accidentally in my setup) then the correct behavior while "Focus Project View after opening/closing file editor" disabled can be noticed.

In the default "Project" view, I can reproduce the described behavior even if "Focus Project View after opening/closing file editor" is disabled.
