### ISSUE TITLE
Using keyboard arrow keys to navigate Project pane, File Preview grabs focus on second file visited

### ISSUE THREAD

**Issue by bronius** [SeeSharpSoft/intellij-file-preview#48]
(see screencast)
![quick-file-preview-focus-grab](https://user-images.githubusercontent.com/2348390/66663596-9f6f1580-ec10-11e9-8a67-d6478531868b.gif)

In the above screencast, I have focus on a folder, arrow down a few times, first non-folder file opens Preview, next non-folder file also opens in Preview but also loses focus. I click a folder to repeat/resume keyboard, same thing.. click one more time this time into file, same thing.

**Comment by SeeSharpSoft** [comment]
Thanks for reporting and the screencast. The editor focus is a tricky one - I couldn't figure out a proper focus behavior yet that works well in every scenario (see #29, #43, #44). I'll keep on investing.

**Comment by oxysoft** [comment]
Also getting this, making the plugin pretty unusable sadly. Hoping it can be fixed!

**Comment by kxalex** [comment]
Looks like it's conflicting with "Autoscroll from source". Try to disable it as it worked for me.

But still, I do want to have it enabled + preview files going through tree.

Looking forward for a fix.
