### ISSUE TITLE
How to change `enter` key to preview, not `space` key?

### ISSUE THREAD

**Issue by pytkr** [SeeSharpSoft/intellij-file-preview#85]
I want to use keyboard only without using mouse clicking, e.g. `enter` key, to **(a)** preview file and **(b)** expand collapsed folder. 
However, the `enter` key can expand collapsed folder, but can't preview file, and the `space` key can preview file, but can't expand collapsed folder.

Otherwise, the `Toggle tree expand/collapse by single click` should be configured to `Toggle tree expand/collapse by space`, thus, the `space` can do both (a) and (b).

**Comment by SeeSharpSoft** [comment]
The `Enter` key is bound to open a file or expand/collapse folders by IntelliJ IDE itself, the `Space` key was meant for an alternate opening of the preview. I noticed, that meanwhile also the `Space` is pre-occupied by the IDE, opening an overflow "Definition" window, so I am considering even removing this option.

When navigating the project view via keyboard, the cursor keys are your friend, where the left-/right-arrow keys provide the full feature set of collapsing/expanding nodes.

**Comment by pytkr** [comment]
> The `Enter` key is bound to open a file or expand/collapse folders by IntelliJ IDE itself, the `Space` key was meant for an alternate opening of the preview. I noticed, that meanwhile also the `Space` is pre-occupied by the IDE, opening an overflow "Definition" window, so I am considering even removing this option.
> 
> When navigating the project view via keyboard, the cursor keys are your friend, where the left-/right-arrow keys provide the full feature set of collapsing/expanding nodes.

Great thanks! The left/right key are exactly what I need!
